[package]
name = "shahmat"
version = "0.1.0"
edition = "2021"
description = "Movegen-correct chess lib, fast with less memory per platform"
license = "Apache-2.0"

[[bin]]
name = "shahmat-svc"
path = "src/main.rs"

[lib]
name = "shahmat"
crate-type = ["cdylib", "rlib"]

[dependencies]
rustler = { version = "0.38", optional = true }

[features]
default = ["magic-black"]
magic-black = []
min-mem = []
nif = ["dep:rustler"]
pext = []

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "debuginfo"
